### ISSUE TITLE
Nav Items is hard to see on mobile

### ISSUE THREAD

**Issue by SamChou19815** [cuappdev/site#20]
Proof:

<img width="590" alt="screen shot 2018-01-28 at 7 52 47 pm" src="https://user-images.githubusercontent.com/4290500/35489439-e311dde4-0464-11e8-8be7-ec541aa2a1c3.png">

Possible solution: 
``` css
@media (max-width: 768px) {
  .navbar-default {
    background-color: white;
  }
  .white-nav-element {
    text-shadow: none;
    color: #666666 !important;
  }
}
```
It may require additional JS support because currently JS will use the position of scroll bar to determine the style of the nav bar.
